# ILANG: ROLE=builder; READ=.ilang/site.ilang + data/offers.json; OUTPUT=site/; NEVER=fake prices
from __future__ import annotations
import html, json, re
from datetime import datetime, timezone
from pathlib import Path
from scraper import parse_config

ROOT=Path(__file__).parent; DATA=ROOT/"data"/"offers.json"; SITE=ROOT/"site"; BASE="https://"+parse_config()["meta"].get("domain","truedealatlas.com").strip().rstrip("/")
def esc(v): return html.escape(str(v), quote=True)
def slug(v):
    value = re.sub(r"[^a-z0-9]+", "-", v.lower()).strip("-") or "item"
    return value[: 95].rstrip("-")
def load_data():
    cfg=parse_config(); payload=json.loads(DATA.read_text(encoding="utf-8")) if DATA.exists() else {"offers":[],"providers":[],"generated_at":datetime.now(timezone.utc).isoformat()}; payload.setdefault("brand",cfg["meta"].get("brand","TrueDealAtlas")); payload.setdefault("niche",cfg["meta"].get("niche","US consumer brand coupons and discounts")); return cfg,payload
def jsonld(obj): return '<script type="application/ld+json">'+json.dumps(obj,ensure_ascii=False)+'</script>'
def page(title,desc,body,path="/",template_name=None):
    canonical=BASE+("/" if path=="/" else path)
    if template_name:
        template_path=ROOT/"templates"/template_name
        if template_path.exists():
            body=template_path.read_text(encoding="utf-8").replace("{{content}}",body)
    return '<!doctype html><html lang="en-US"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{}</title><meta name="description" content="{}"><link rel="canonical" href="{}"><meta property="og:title" content="{}"><meta property="og:description" content="{}"><meta property="og:url" content="{}"><meta name="twitter:card" content="summary"><link rel="stylesheet" href="/styles.css"></head><body><header><a class="brand" href="/">TrueDealAtlas</a><nav><a href="/">Deals</a><a href="/compare.html">Compare</a><a href="/providers/">Providers</a><a href="/about.html">About</a><a href="/privacy.html">Privacy</a><a href="/contact.html">Contact</a></nav></header><main>{}</main><footer>Independent index of public, official offer pages. Verify terms at the source before purchase. <a href="/about.html">About</a> <a href="/privacy.html">Privacy</a> <a href="/contact.html">Contact</a> <a href="/.ilang/site.ilang">Site rules</a></footer></body></html>'.format(esc(title),esc(desc),esc(canonical),esc(title),esc(desc),esc(canonical),body)
def offer_card(o):
    detail="/deals/{}-{}.html".format(slug(o["provider"]),slug(o["title"])); value="{}% off".format(o["discount_percent"]) if o.get("discount_percent") else ("USD {}".format(o["price"]) if o.get("price") else "Official offer")
    return '<article class="deal"><span class="tag">{}</span><h3><a href="{}">{}</a></h3><p class="muted">Checked {}</p><a class="button" href="{}" rel="nofollow noopener">View at {}</a></article>'.format(esc(value),detail,esc(o["title"]),esc(o.get("fetched_at","")),esc(o["offer_url"]),esc(o["provider"]))
def build():
    cfg,data=load_data(); SITE.mkdir(exist_ok=True); (SITE/"providers").mkdir(exist_ok=True); (SITE/"deals").mkdir(exist_ok=True); (SITE/"styles.css").write_text(STYLES,encoding="utf-8")
    offers=[o for o in data.get("offers",[]) if o.get("active",True)]; cards="".join(offer_card(o) for o in offers[:60]) or '<div class="empty"><h2>No active offers detected yet</h2><p>We only publish deals found on official provider pages. Check back after the next scheduled refresh.</p></div>'
    body='<section class="hero"><p class="eyebrow">US consumer brand savings</p><h1>TrueDealAtlas</h1><p>Official sale pages and public promotions, checked automatically every six hours.</p></section><section><div class="section-head"><h2>Latest verified finds</h2><span class="muted">{} active</span></div><div class="grid">{}</div></section><section class="sources"><h2>Source coverage</h2><p>We check {} official offer pages. A source can be healthy even when it has no parseable promotion.</p><a href="/providers/">Browse providers and source status</a></section>'.format(len(offers),cards,len(data.get("providers",[])))
    (SITE/"index.html").write_text(page("TrueDealAtlas | Official US Deals","A transparent index of official US consumer brand offers and sale pages.",body,template_name="index.html"),encoding="utf-8")
    about_body='''<article class="detail"><p class="eyebrow">About TrueDealAtlas</p><h1>About TrueDealAtlas</h1><p>TrueDealAtlas is an independent index of public sale pages and promotions from US consumer brands.</p><h2>Where the data comes from</h2><p>Every listing begins with a public, official brand source such as a sale page, sitemap, or feed. We do not invent offers, prices, expiration dates, or commission claims. When a source does not expose a reliable detail, we leave it out.</p><h2>How often sources are checked</h2><p>Our deterministic Python update pipeline checks configured official sources every six hours and rebuilds the static site from the results.</p><h2>Who maintains the site</h2><p>TrueDealAtlas is maintained by its owner with an automated, source-traceable publishing workflow. Questions and corrections are welcome through the <a href="/contact.html">contact page</a>.</p><p><a href="/privacy.html">Privacy</a> · <a href="/contact.html">Contact</a></p></article>'''
    privacy_body='''<article class="detail"><p class="eyebrow">Site policy</p><h1>Privacy Policy</h1><p>Last updated: September 16, 2026.</p><h2>Information we do not collect</h2><p>TrueDealAtlas does not offer user accounts, accept payments, or use a contact form. We do not intentionally collect names, postal addresses, payment details, or other personal information through this site.</p><h2>Hosting and measurement</h2><p>The site does not currently load a separate analytics service or advertising tracker. Cloudflare hosts and delivers the site and may process basic request and security data under its own policies.</p><h2>Outbound and affiliate links</h2><p>Links can take you to official third-party websites, which have their own privacy practices. TrueDealAtlas may use affiliate links. When a link is an affiliate link, it will be disclosed clearly; a qualifying purchase may earn the site a commission at no additional cost to you.</p><h2>Questions</h2><p>For privacy questions, use the <a href="/contact.html">contact page</a>.</p><p><a href="/about.html">About</a> · <a href="/contact.html">Contact</a></p></article>'''
    contact_body='''<article class="detail"><p class="eyebrow">Get in touch</p><h1>Contact TrueDealAtlas</h1><p>Email <a href="mailto:contact@truedealatlas.com">contact@truedealatlas.com</a>. We aim to reply within three business days.</p><p><a href="/about.html">About</a> · <a href="/privacy.html">Privacy</a></p></article>'''
    (SITE/"about.html").write_text(page("About TrueDealAtlas","How TrueDealAtlas sources and checks official US brand offers.",about_body,"/about.html"),encoding="utf-8")
    (SITE/"privacy.html").write_text(page("Privacy Policy | TrueDealAtlas","Privacy, hosting, analytics, and affiliate disclosure for TrueDealAtlas.",privacy_body,"/privacy.html"),encoding="utf-8")
    (SITE/"contact.html").write_text(page("Contact TrueDealAtlas","How to contact TrueDealAtlas about corrections and questions.",contact_body,"/contact.html"),encoding="utf-8")
    links=[]
    for p in data.get("providers",[]):
        ps=slug(p["name"]); po=[o for o in offers if o.get("provider")==p["name"]]; pbody='<section class="hero compact"><p class="eyebrow">Official source</p><h1>{}</h1><p>{} active offers indexed.</p><a class="button" href="{}" rel="nofollow noopener">Open official page</a></section><section><h2>Indexed offers</h2><div class="grid">{}</div></section>'.format(esc(p["name"]),len(po),esc(p["source_url"]),"".join(offer_card(o) for o in po) or '<p class="muted">No active offer text detected on the last check.</p>')
        if po:
            prices=[float(o["price"]) for o in po if o.get("price")]
            p_schema={"@context":"https://schema.org","@type":"Product","name":p["name"],"url":BASE+"/providers/"+ps+".html","offers":{"@type":"AggregateOffer","offerCount":len(po)}}
            if prices:
                p_schema["offers"].update({"lowPrice":min(prices),"highPrice":max(prices),"priceCurrency":"USD"})
            pbody += jsonld(p_schema)
        (SITE/"providers"/(ps+".html")).write_text(page(p["name"]+" Deals | TrueDealAtlas","Official {} sale and promotion source status.".format(p["name"]),pbody,"/providers/"+ps+".html","provider.html"),encoding="utf-8"); links.append('<li><a href="/providers/{}.html">{}</a> <span class="muted">{}, {} offers</span></li>'.format(ps,esc(p["name"]),p.get("status","unknown"),p.get("offer_count",0)))
    (SITE/"providers"/"index.html").write_text(page("Providers | TrueDealAtlas","Official provider pages checked by TrueDealAtlas",'<section class="hero compact"><h1>Providers</h1><p>Every link below points to an official brand source.</p></section><ul class="provider-list">{}</ul>'.format("".join(links)),"/providers/","provider.html"),encoding="utf-8")
    rows="".join('<tr><td>{}</td><td><a href="/deals/{}-{}.html">{}</a></td><td>{}%</td></tr>'.format(esc(o["provider"]),slug(o["provider"]),slug(o["title"]),esc(o["title"]),esc(o.get("discount_percent",""))) for o in offers)
    item_list={"@context":"https://schema.org","@type":"ItemList","itemListElement":[{"@type":"ListItem","position":i,"url":BASE+"/deals/{}-{}.html".format(slug(o["provider"]),slug(o["title"]))} for i,o in enumerate(offers,1)]}
    compare_body='<section class="hero compact"><h1>Compare active deals</h1></section><table><thead><tr><th>Provider</th><th>Offer</th><th>Discount</th></tr></thead><tbody>{}</tbody></table>{}'.format(rows or '<tr><td colspan="3">No active offers detected.</td></tr>',jsonld(item_list))
    (SITE/"compare.html").write_text(page("Compare Deals | TrueDealAtlas","Compare currently active official promotions",compare_body,"/compare.html","compare.html"),encoding="utf-8")
    for o in offers:
        path="/deals/{}-{}.html".format(slug(o["provider"]),slug(o["title"])); fields={"price":o["price"],"priceCurrency":o["currency"]} if o.get("price") and o.get("currency") else {}; schema={"@context":"https://schema.org","@type":"Offer","name":o["title"],"url":BASE+path,"availability":"https://schema.org/InStock","seller":{"@type":"Organization","name":o["provider"]},**fields}; dbody='<article class="detail"><p class="eyebrow">{}</p><h1>{}</h1><p>Indexed from the official source on {}.</p><a class="button" href="{}" rel="nofollow noopener">Check offer at {}</a><p class="source">Source: <a href="{}">{}</a></p>{}</article>'.format(esc(o["provider"]),esc(o["title"]),esc(o.get("fetched_at","")),esc(o["offer_url"]),esc(o["provider"]),esc(o["source_url"]),esc(o["source_url"]),jsonld(schema)); target=SITE/path.lstrip("/"); target.parent.mkdir(parents=True,exist_ok=True); target.write_text(page(o["provider"]+" Offer | TrueDealAtlas",o["title"]+" from "+o["provider"]+", checked from the official source.",dbody,path),encoding="utf-8")
    urls=["/","/compare.html","/providers/","/about.html","/privacy.html","/contact.html"]+["/providers/{}.html".format(slug(p["name"])) for p in data.get("providers",[])]+["/deals/{}-{}.html".format(slug(o["provider"]),slug(o["title"])) for o in offers]; lastmod=esc(data.get("generated_at",datetime.now(timezone.utc).isoformat())); (SITE/"sitemap.xml").write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+"".join("<url><loc>{}{}</loc><lastmod>{}</lastmod></url>".format(BASE,u,lastmod) for u in urls)+"</urlset>",encoding="utf-8"); (SITE/"robots.txt").write_text("User-agent: *\nAllow: /\nSitemap: {}/sitemap.xml\n".format(BASE),encoding="utf-8"); (SITE/".ilang").mkdir(exist_ok=True); (SITE/".ilang"/"site.ilang").write_text((ROOT/".ilang"/"site.ilang").read_text(encoding="utf-8"),encoding="utf-8")
STYLES='''*{box-sizing:border-box}body{margin:0;font:16px/1.6 system-ui,-apple-system,Segoe UI,sans-serif;color:#16202a;background:#f7f8f5}a{color:#0a6474}header,main,footer{max-width:1120px;margin:auto;padding:0 24px}header{height:72px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #d9e1df}.brand{font-weight:800;text-decoration:none;color:#16202a;font-size:1.15rem}nav{display:flex;gap:20px}nav a{text-decoration:none;color:#46545b}.hero{padding:72px 0 56px;max-width:760px}.hero.compact{padding:48px 0 28px}.eyebrow,.tag{color:#c54b2c;text-transform:uppercase;letter-spacing:.08em;font-size:.78rem;font-weight:800}.hero h1{font-size:clamp(2.4rem,6vw,5rem);line-height:1.02;margin:.2em 0}.hero p{font-size:1.2rem;color:#526067}.section-head{display:flex;justify-content:space-between;align-items:baseline}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:16px}.deal{background:#fff;border:1px solid #d9e1df;padding:20px;border-radius:6px}.deal h3{font-size:1.08rem;line-height:1.3}.muted{color:#69767b;font-size:.88rem}.button{display:inline-block;background:#0a6474;color:#fff;padding:9px 13px;border-radius:4px;text-decoration:none;font-weight:700}.sources{border-top:1px solid #d9e1df;margin:64px 0;padding:28px 0}.empty{padding:32px;background:#fff;border:1px dashed #b9c7c5}.provider-list{padding:0;list-style:none;columns:2}.provider-list li{padding:9px 0;border-bottom:1px solid #e3e8e6}table{width:100%;border-collapse:collapse;background:#fff}th,td{text-align:left;padding:12px;border-bottom:1px solid #d9e1df}.detail{padding:50px 0 100px;max-width:760px}.source{margin-top:36px;font-size:.9rem;overflow-wrap:anywhere}footer{border-top:1px solid #d9e1df;padding-top:24px;padding-bottom:40px;color:#69767b;font-size:.85rem}@media(max-width:650px){header{height:auto;padding-top:18px;padding-bottom:18px;display:block}nav{margin-top:10px;gap:14px}.provider-list{columns:1}.hero{padding-top:48px}}'''
if __name__ == "__main__": build()
